name: Run Hust Register On GitHub Action
on:
  # push:
  workflow_dispatch:
  schedule:
  # 定时任务，在每天的6点定时登记
    - cron: '0 22 * * *'
jobs:
  HustRegister:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay ddddocr
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Python script
        run: python register.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} ${{ secrets.REGISTERURL }}
      
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: commit
        run: |
          # Stage the file, commit and push
          git add -A
          git commit -m "GitHub Actions Results added"
          git push
